### ISSUE TITLE
RAML 1.0 support

### ISSUE THREAD

**Issue by meetmangukiya** [val314159/raml-python#5]

**Comment by val314159** [comment]
are you saying there are missing features, or it just completely doesnt work at all?

**Comment by meetmangukiya** [comment]
Doesn't work at all

**Comment by meetmangukiya** [comment]
> 
```
± % node_modules/.bin/raml-python-generator webservices.raml.yaml -o coala-webservices                                                                !10106
YAMLError: Unsupported RAML version: '#%RAML 1.0'
    at Constructor.__dirname.Scanner.Scanner.scan_to_next_token (/sub/ghubby/coala/corobo/node_modules/raml-parser/lib/scanner.js:720:21)
    at Constructor.__dirname.Scanner.Scanner.fetch_more_tokens (/sub/ghubby/coala/corobo/node_modules/raml-parser/lib/scanner.js:183:12)
    at Constructor.__dirname.Scanner.Scanner.check_token (/sub/ghubby/coala/corobo/node_modules/raml-parser/lib/scanner.js:122:14)
    at Constructor.__dirname.Parser.Parser.parse_implicit_document_start (/sub/ghubby/coala/corobo/node_modules/raml-parser/lib/parser.js:126:17)
    at Constructor.__dirname.Parser.Parser.check_event (/sub/ghubby/coala/corobo/node_modules/raml-parser/lib/parser.js:62:48)
    at Constructor.__dirname.Composer.Composer.getYamlRoot (/sub/ghubby/coala/corobo/node_modules/raml-parser/lib/composer.js:60:17)
    at /sub/ghubby/coala/corobo/node_modules/raml-parser/lib/raml.js:226:23
    at Promise.apply (/sub/ghubby/coala/corobo/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (/sub/ghubby/coala/corobo/node_modules/q/q.js:752:41)
    at /sub/ghubby/coala/corobo/node_modules/q/q.js:1337:14
```

**Comment by val314159** [comment]
If you give me a simple test i'll see what i can do.  Seems like it's bubbling up from a lower level.

**Comment by meetmangukiya** [comment]
https://gist.github.com/meetmangukiya/711fe592dad2b522b923f87e0fcace56

**Comment by val314159** [comment]
Ugh.  The parser this sits on top of is a mess.  maybe if you update that to take the new RAML version it will work..... but maybe not :(
